export const searchResults = {
  worldAutocomplete: {
    data: {
      ACCOUNT: [
        {
          address: 'world',
          balances: { 'USD/2': -2124380, USD: -1573 },
          metadata: {
            '11': 'y',
            '0': 'T',
            'super/cle': { super: 'toto2' },
            '10': 'B',
          },
          volumes: {
            'USD/2': { output: 2124380, input: 0 },
            USD: { output: 1573, input: 0 },
          },
        },
      ],
      ASSET: [
        { account: 'world', input: 0, name: 'USD', output: 1573 },
        {
          account: 'world',
          input: 0,
          name: 'USD/2',
          output: 2124380,
        },
      ],
      PAYMENT: [
        {
          date: '0001-01-01T00:00:00Z',
          id: 'driver',
          provider: 'Stripe',
          raw: null,
          reference: 'payment',
          scheme: '',
          status: 'completed',
          type: 'payout',
          value: { amount: 393, asset: 'USD/2' },
        },
      ],
      TRANSACTION: [
        {
          metadata: {},
          postings: [
            {
              amount: 421,
              asset: 'USD',
              destination: 'central_bank',
              source: 'world',
            },
          ],
          reference: 'New',
          timestamp: '2022-05-04T08:59:10Z',
          txid: 4,
        },
        {
          metadata: {},
          postings: [
            {
              amount: 37,
              asset: 'USD',
              destination: 'central_bank',
              source: 'world',
            },
          ],
          reference: 'JBOD',
          timestamp: '2022-05-04T08:59:07Z',
          txid: 3,
        },
        {
          metadata: {},
          postings: [
            {
              amount: 69,
              asset: 'USD',
              destination: 'central_bank',
              source: 'world',
            },
          ],
          reference: 'Market',
          timestamp: '2022-05-04T08:49:28Z',
          txid: 2,
        },
      ],
    },
  },
  worldAccountSearch: {
    cursor: {
      pageSize: 1,
      hasMore: false,
      total: { value: 1, relation: 'eq' },
      data: [
        {
          balances: { USD: -1573, 'USD/2': -2124380 },
          metadata: {
            '11': 'y',
            '12': '2',
            '13': '3',
            aller: 'toto',
            '0': 'T',
            'super/cle': { super: 'toto2' },
            '1': 'o',
            '2': 'u',
            '3': 't',
            '4': 'r',
            top: '"controlledBy20"',
            '5': 'o',
            '6': 'l',
            '7': 'l',
            '8': 'e',
            '9': 'd',
            value: 'controlledBy99',
            key: 'titi',
            '10': 'B',
          },
          address: 'world',
          volumes: {
            USD: { output: 1573, input: 0 },
            'USD/2': { output: 2124380, input: 0 },
          },
        },
      ],
      previous: '',
    },
  },
  worldTransactionSearch: {
    cursor: {
      pageSize: 15,
      hasMore: true,
      total: { value: 1726, relation: 'eq' },
      next: 'eyJ0YXJnZXQiOiJUUkFOU0FDVElPTiIsInNvcnQiOlt7ImtleSI6InR4aWQiLCJvcmRlciI6ImRlc2MifV0sInNlYXJjaEFmdGVyIjpbMjcyMV0sImxlZGdlcnMiOlsidm9vLTg5MDg0OTk1Il0sInNpemUiOjE1LCJ0ZXJtUG9saWN5IjoiIiwicmV2ZXJzZSI6ZmFsc2UsInRlcm1zIjpbIndvcmxkIl19Cg==',
      data: [
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 186,
              destination: 'payments:580305',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 186,
              destination: 'orders:792607',
              source: 'payments:580305',
              asset: 'USD/2',
            },
          ],
          txid: 2741,
          timestamp: '2021-12-28T09:30:16Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1927,
              destination: 'payments:475759',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1927,
              destination: 'orders:999641',
              source: 'payments:475759',
              asset: 'USD/2',
            },
          ],
          txid: 2739,
          timestamp: '2021-12-28T09:30:16Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 248,
              destination: 'payments:895757',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 248,
              destination: 'orders:296777',
              source: 'payments:895757',
              asset: 'USD/2',
            },
          ],
          txid: 2737,
          timestamp: '2021-12-28T09:30:15Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1096,
              destination: 'payments:143568',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1096,
              destination: 'orders:603352',
              source: 'payments:143568',
              asset: 'USD/2',
            },
          ],
          txid: 2735,
          timestamp: '2021-12-28T09:30:15Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1544,
              destination: 'payments:494884',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1544,
              destination: 'orders:611392',
              source: 'payments:494884',
              asset: 'USD/2',
            },
          ],
          txid: 2734,
          timestamp: '2021-12-28T09:30:14Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 67,
              destination: 'payments:862401',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 67,
              destination: 'orders:258660',
              source: 'payments:862401',
              asset: 'USD/2',
            },
          ],
          txid: 2733,
          timestamp: '2021-12-28T09:30:14Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 2469,
              destination: 'payments:945496',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 2469,
              destination: 'orders:376060',
              source: 'payments:945496',
              asset: 'USD/2',
            },
          ],
          txid: 2732,
          timestamp: '2021-12-28T09:30:14Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1253,
              destination: 'payments:843469',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1253,
              destination: 'orders:766291',
              source: 'payments:843469',
              asset: 'USD/2',
            },
          ],
          txid: 2730,
          timestamp: '2021-12-28T09:30:13Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1375,
              destination: 'payments:923783',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1375,
              destination: 'orders:719952',
              source: 'payments:923783',
              asset: 'USD/2',
            },
          ],
          txid: 2729,
          timestamp: '2021-12-28T09:30:12Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1453,
              destination: 'payments:239984',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1453,
              destination: 'orders:156546',
              source: 'payments:239984',
              asset: 'USD/2',
            },
          ],
          txid: 2727,
          timestamp: '2021-12-28T09:30:12Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 609,
              destination: 'payments:029239',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 609,
              destination: 'orders:807886',
              source: 'payments:029239',
              asset: 'USD/2',
            },
          ],
          txid: 2725,
          timestamp: '2021-12-28T09:30:12Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1729,
              destination: 'payments:601230',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1729,
              destination: 'orders:379702',
              source: 'payments:601230',
              asset: 'USD/2',
            },
          ],
          txid: 2724,
          timestamp: '2021-12-28T09:30:11Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 132,
              destination: 'payments:143686',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 132,
              destination: 'orders:197717',
              source: 'payments:143686',
              asset: 'USD/2',
            },
          ],
          txid: 2723,
          timestamp: '2021-12-28T09:30:11Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1207,
              destination: 'payments:785447',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1207,
              destination: 'orders:189905',
              source: 'payments:785447',
              asset: 'USD/2',
            },
          ],
          txid: 2722,
          timestamp: '2021-12-28T09:30:11Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1047,
              destination: 'payments:644955',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1047,
              destination: 'orders:830414',
              source: 'payments:644955',
              asset: 'USD/2',
            },
          ],
          txid: 2721,
          timestamp: '2021-12-28T09:30:10Z',
        },
      ],
      previous: '',
    },
  },
  paymentsFirstPage: {
    cursor: {
      pageSize: 15,
      hasMore: true,
      total: { value: 21, relation: 'eq' },
      next: 'eyJ0YXJnZXQiOiJQQVlNRU5UIiwic29ydCI6W10sInNlYXJjaEFmdGVyIjpudWxsLCJsZWRnZXJzIjpudWxsLCJzaXplIjoxNSwidGVybVBvbGljeSI6IiIsInJldmVyc2UiOmZhbHNlLCJ0ZXJtcyI6WyJ0eXBlPXBheS1pbiIsIiJdfQo=',
      data: [
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'compressing',
          scheme: '',
          provider: 'Paypal',
          raw: null,
          id: 'Fresh',
          type: 'pay-in',
          value: { amount: 344, asset: 'USD' },
          status: 'authorized',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'protocol',
          scheme: '',
          provider: 'Paypal',
          raw: null,
          id: 'task-force',
          type: 'pay-in',
          value: { amount: 292, asset: 'USD' },
          status: 'refunded',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'BCEAO',
          scheme: '',
          provider: 'Stripe',
          raw: null,
          id: 'indexing',
          type: 'pay-in',
          value: { amount: 846, asset: 'USD/2' },
          status: 'completed',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'Manors',
          scheme: '',
          provider: 'Stripe',
          raw: null,
          id: 'Forges',
          type: 'pay-in',
          value: { amount: 570, asset: 'USD/2' },
          status: 'completed',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'green',
          scheme: '',
          provider: 'Stripe',
          raw: null,
          id: 'Direct',
          type: 'pay-in',
          value: { amount: 209, asset: 'USD/2' },
          status: 'completed',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'Branding',
          scheme: '',
          provider: 'Stripe',
          raw: null,
          id: 'withdrawal',
          type: 'pay-in',
          value: { amount: 906, asset: 'USD/2' },
          status: 'completed',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'Roads',
          scheme: '',
          provider: 'Paypal',
          raw: null,
          id: 'quantifying',
          type: 'pay-in',
          value: { amount: 578, asset: 'USD' },
          status: 'refunded',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'Pants',
          scheme: '',
          provider: 'Paypal',
          raw: null,
          id: 'Rand',
          type: 'pay-in',
          value: { amount: 453, asset: 'USD' },
          status: 'refunded',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'Legacy',
          scheme: '',
          provider: 'Stripe',
          raw: null,
          id: 'PNG',
          type: 'pay-in',
          value: { amount: 209, asset: 'USD/2' },
          status: 'completed',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'Maldives',
          scheme: '',
          provider: 'Stripe',
          raw: null,
          id: 'Games',
          type: 'pay-in',
          value: { amount: 970, asset: 'USD/2' },
          status: 'completed',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'Granite',
          scheme: '',
          provider: 'Stripe',
          raw: null,
          id: 'Wooden',
          type: 'pay-in',
          value: { amount: 960, asset: 'USD/2' },
          status: 'completed',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'quantifying',
          scheme: '',
          provider: 'Paypal',
          raw: null,
          id: 'parsing',
          type: 'pay-in',
          value: { amount: 570, asset: 'USD' },
          status: 'authorized',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'high-level',
          scheme: '',
          provider: 'Paypal',
          raw: null,
          id: 'Buckinghamshire',
          type: 'pay-in',
          value: { amount: 40, asset: 'USD' },
          status: 'authorized',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'Virginia',
          scheme: '',
          provider: 'Stripe',
          raw: null,
          id: 'Operations',
          type: 'pay-in',
          value: { amount: 371, asset: 'USD/2' },
          status: 'completed',
        },
        {
          date: '0001-01-01T00:00:00Z',
          reference: 'Nauru',
          scheme: '',
          provider: 'Stripe',
          raw: null,
          id: 'compress',
          type: 'pay-in',
          value: { amount: 157, asset: 'USD/2' },
          status: 'completed',
        },
      ],
      previous:
        'eyJ0YXJnZXQiOiJQQVlNRU5UIiwic29ydCI6W10sInNlYXJjaEFmdGVyIjpudWxsLCJsZWRnZXJzIjpudWxsLCJzaXplIjoxNSwidGVybVBvbGljeSI6IiIsInJldmVyc2UiOnRydWUsInRlcm1zIjpbInR5cGU9cGF5LWluIiwiIl19Cg==',
    },
  },
  accountsFirstPage: {
    cursor: {
      pageSize: 15,
      hasMore: true,
      total: { value: 3552, relation: 'eq' },
      next: 'eyJ0YXJnZXQiOiJBQ0NPVU5UIiwic29ydCI6W3sia2V5IjoiYWRkcmVzcyIsIm9yZGVyIjoiZGVzYyJ9XSwic2VhcmNoQWZ0ZXIiOlsicGF5bWVudHM6OTk2MjY2Il0sImxlZGdlcnMiOlsidm9vLTg5MDg0OTk1Il0sInNpemUiOjE1LCJ0ZXJtUG9saWN5IjoiIiwicmV2ZXJzZSI6ZmFsc2UsInRlcm1zIjpudWxsfQo=',
      data: [
        { balances: {}, metadata: {}, address: 'zaza', volumes: {} },
        {
          balances: {
            USD: -1573,
            'USD/2': -2124380,
          },
          metadata: {
            '11': 'y',
            '0': 'T',
            'super/cle': { super: 'toto2' },
            '10': 'B',
          },
          address: 'world',
          volumes: {
            USD: { output: 1573, input: 0 },
            'USD/2': { output: 2124380, input: 0 },
          },
        },
        {
          balances: { 'USD/2': 38322 },
          metadata: {},
          address: 'taxes',
          volumes: { 'USD/2': { output: 0, input: 38322 } },
        },
        {
          balances: { 'USD/2': 151210 },
          metadata: {},
          address: 'platform',
          volumes: { 'USD/2': { output: 0, input: 151210 } },
        },
        {
          balances: { 'USD/2': 0 },
          metadata: {},
          address: 'payments:999248',
          volumes: { 'USD/2': { output: 732, input: 732 } },
        },
        {
          balances: { 'USD/2': 0 },
          metadata: {},
          address: 'payments:998666',
          volumes: { 'USD/2': { output: 506, input: 506 } },
        },
        {
          balances: { 'USD/2': 0 },
          metadata: {},
          address: 'payments:998596',
          volumes: { 'USD/2': { output: 1726, input: 1726 } },
        },
        {
          balances: { 'USD/2': 0 },
          metadata: {},
          address: 'payments:998467',
          volumes: { 'USD/2': { output: 135, input: 135 } },
        },
        {
          balances: { 'USD/2': 0 },
          metadata: {},
          address: 'payments:998394',
          volumes: { 'USD/2': { output: 111, input: 111 } },
        },
        {
          balances: { 'USD/2': 0 },
          metadata: {},
          address: 'payments:998355',
          volumes: { 'USD/2': { output: 1543, input: 1543 } },
        },
        {
          balances: { 'USD/2': 0 },
          metadata: {},
          address: 'payments:998073',
          volumes: { 'USD/2': { output: 1900, input: 1900 } },
        },
        {
          balances: { 'USD/2': 0 },
          metadata: {},
          address: 'payments:996845',
          volumes: { 'USD/2': { output: 2481, input: 2481 } },
        },
        {
          balances: { 'USD/2': 0 },
          metadata: {},
          address: 'payments:996572',
          volumes: { 'USD/2': { output: 2074, input: 2074 } },
        },
        {
          balances: { 'USD/2': 0 },
          metadata: {},
          address: 'payments:996497',
          volumes: { 'USD/2': { output: 1142, input: 1142 } },
        },
        {
          balances: { 'USD/2': 0 },
          metadata: {},
          address: 'payments:996266',
          volumes: { 'USD/2': { output: 2431, input: 2431 } },
        },
      ],
      previous: '',
    },
  },
  transactionsFirstPage: {
    cursor: {
      pageSize: 15,
      hasMore: true,
      total: { value: 2742, relation: 'eq' },
      next: 'eyJ0YXJnZXQiOiJUUkFOU0FDVElPTiIsInNvcnQiOlt7ImtleSI6InR4aWQiLCJvcmRlciI6ImRlc2MifV0sInNlYXJjaEFmdGVyIjpbMjcyN10sImxlZGdlcnMiOlsidm9vLTg5MDg0OTk1Il0sInNpemUiOjE1LCJ0ZXJtUG9saWN5IjoiIiwicmV2ZXJzZSI6ZmFsc2UsInRlcm1zIjpudWxsfQo=',
      data: [
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 186,
              destination: 'payments:580305',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 186,
              destination: 'orders:792607',
              source: 'payments:580305',
              asset: 'USD/2',
            },
          ],
          txid: 2741,
          timestamp: '2021-12-28T09:30:16Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 20,
              destination: 'taxes',
              source: 'orders:999641',
              asset: 'USD/2',
            },
            {
              amount: 77,
              destination: 'platform',
              source: 'orders:999641',
              asset: 'USD/2',
            },
            {
              amount: 1830,
              destination: 'merchants:41',
              source: 'orders:999641',
              asset: 'USD/2',
            },
          ],
          txid: 2740,
          timestamp: '2021-12-28T09:30:16Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1927,
              destination: 'payments:475759',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1927,
              destination: 'orders:999641',
              source: 'payments:475759',
              asset: 'USD/2',
            },
          ],
          txid: 2739,
          timestamp: '2021-12-28T09:30:16Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 6,
              destination: 'taxes',
              source: 'orders:296777',
              asset: 'USD/2',
            },
            {
              amount: 22,
              destination: 'platform',
              source: 'orders:296777',
              asset: 'USD/2',
            },
            {
              amount: 220,
              destination: 'merchants:56',
              source: 'orders:296777',
              asset: 'USD/2',
            },
          ],
          txid: 2738,
          timestamp: '2021-12-28T09:30:16Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 248,
              destination: 'payments:895757',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 248,
              destination: 'orders:296777',
              source: 'payments:895757',
              asset: 'USD/2',
            },
          ],
          txid: 2737,
          timestamp: '2021-12-28T09:30:15Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 27,
              destination: 'taxes',
              source: 'orders:603352',
              asset: 'USD/2',
            },
            {
              amount: 105,
              destination: 'platform',
              source: 'orders:603352',
              asset: 'USD/2',
            },
            {
              amount: 964,
              destination: 'merchants:10',
              source: 'orders:603352',
              asset: 'USD/2',
            },
          ],
          txid: 2736,
          timestamp: '2021-12-28T09:30:15Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1096,
              destination: 'payments:143568',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1096,
              destination: 'orders:603352',
              source: 'payments:143568',
              asset: 'USD/2',
            },
          ],
          txid: 2735,
          timestamp: '2021-12-28T09:30:15Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1544,
              destination: 'payments:494884',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1544,
              destination: 'orders:611392',
              source: 'payments:494884',
              asset: 'USD/2',
            },
          ],
          txid: 2734,
          timestamp: '2021-12-28T09:30:14Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 67,
              destination: 'payments:862401',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 67,
              destination: 'orders:258660',
              source: 'payments:862401',
              asset: 'USD/2',
            },
          ],
          txid: 2733,
          timestamp: '2021-12-28T09:30:14Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 2469,
              destination: 'payments:945496',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 2469,
              destination: 'orders:376060',
              source: 'payments:945496',
              asset: 'USD/2',
            },
          ],
          txid: 2732,
          timestamp: '2021-12-28T09:30:14Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 43,
              destination: 'taxes',
              source: 'orders:766291',
              asset: 'USD/2',
            },
            {
              amount: 171,
              destination: 'platform',
              source: 'orders:766291',
              asset: 'USD/2',
            },
            {
              amount: 1039,
              destination: 'merchants:43',
              source: 'orders:766291',
              asset: 'USD/2',
            },
          ],
          txid: 2731,
          timestamp: '2021-12-28T09:30:13Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1253,
              destination: 'payments:843469',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1253,
              destination: 'orders:766291',
              source: 'payments:843469',
              asset: 'USD/2',
            },
          ],
          txid: 2730,
          timestamp: '2021-12-28T09:30:13Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1375,
              destination: 'payments:923783',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1375,
              destination: 'orders:719952',
              source: 'payments:923783',
              asset: 'USD/2',
            },
          ],
          txid: 2729,
          timestamp: '2021-12-28T09:30:12Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 9,
              destination: 'taxes',
              source: 'orders:156546',
              asset: 'USD/2',
            },
            {
              amount: 35,
              destination: 'platform',
              source: 'orders:156546',
              asset: 'USD/2',
            },
            {
              amount: 1409,
              destination: 'merchants:49',
              source: 'orders:156546',
              asset: 'USD/2',
            },
          ],
          txid: 2728,
          timestamp: '2021-12-28T09:30:12Z',
        },
        {
          reference: null,
          metadata: {},
          postings: [
            {
              amount: 1453,
              destination: 'payments:239984',
              source: 'world',
              asset: 'USD/2',
            },
            {
              amount: 1453,
              destination: 'orders:156546',
              source: 'payments:239984',
              asset: 'USD/2',
            },
          ],
          txid: 2727,
          timestamp: '2021-12-28T09:30:12Z',
        },
      ],
      previous: '',
    },
  },
  accountWorldDetails: {
    cursor: {
      pageSize: 1,
      hasMore: false,
      total: { value: 1, relation: 'eq' },
      data: [
        {
          balances: { USD: -1573, 'USD/2': -2124380 },
          metadata: {
            '11': 'y',
            '0': 'T',
            'super/cle': { super: 'toto2' },
            '10': 'B',
          },
          address: 'world',
          volumes: {
            USD: { output: 1573, input: 0 },
            'USD/2': { output: 2124380, input: 0 },
          },
        },
      ],
      previous: '',
    },
  },
  accountWorldDetailsAssets: {
    cursor: {
      pageSize: 2,
      hasMore: false,
      total: { value: 2, relation: 'eq' },
      data: [
        { output: 1573, input: 0, name: 'USD', account: 'world' },
        {
          output: 2124380,
          input: 0,
          name: 'USD/2',
          account: 'world',
        },
      ],
      previous: '',
    },
  },
};
