version: '3.8'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
    - 9411:9411/tcp
  collector:
    image: otel/opentelemetry-collector
    volumes:
    - ./otel-config.yml:/etc/otelcol/config.yaml
    ports:
    - 4317:4317
