import { range } from "lodash";

export const LEDGER_SLUG = "foo-x-1";

export const account = {
  ledger: LEDGER_SLUG,
  address: "world",
  metadata: {},
  volumes: {
    "EUR/2": {
      input: 0,
      output: 10000000,
      balance: -10000000,
    },
    "RBLX/6": {
      input: 0,
      output: 350000000,
      balance: -350000000,
    },
    "SNAP/6": {
      input: 0,
      output: 1840000000,
      balance: -1840000000,
    },
  },
  balances: {
    "EUR/2": -10000000,
    "RBLX/6": -350000000,
    "SNAP/6": -1840000000,
  },
};
export const transaction = {
  ledger: LEDGER_SLUG,
  postings: [
    {
      source: "world",
      destination: "teller:otc:nyse",
      amount: 350000,
      asset: "RBLX/6",
    },
    {
      source: "world",
      destination: "teller:otc:nyse",
      amount: 1840000,
      asset: "SNAP/6",
    },
  ],
  reference: "",
  metadata: {},
  txid: 6995,
  timestamp: "2022-08-18T14:44:06Z",
  preCommitVolumes: {
    "teller:otc:nyse": {
      "RBLX/6": {
        input: 349650000,
        output: 349650000,
        balance: 0,
      },
      "SNAP/6": {
        input: 1838160000,
        output: 1838160000,
        balance: 0,
      },
    },
    world: {
      "RBLX/6": {
        input: 0,
        output: 349650000,
        balance: -349650000,
      },
      "SNAP/6": {
        input: 0,
        output: 1838160000,
        balance: -1838160000,
      },
    },
  },
  postCommitVolumes: {
    "teller:otc:nyse": {
      "RBLX/6": {
        input: 350000000,
        output: 349650000,
        balance: 350000,
      },
      "SNAP/6": {
        input: 1840000000,
        output: 1838160000,
        balance: 1840000,
      },
    },
    world: {
      "RBLX/6": {
        input: 0,
        output: 350000000,
        balance: -350000000,
      },
      "SNAP/6": {
        input: 0,
        output: 1840000000,
        balance: -1840000000,
      },
    },
  },
};
export const payment = {
  id: "eyJwcm92aWRlciI6InN0cmlwZSIXVQaUZxVzAzWllpTm4wdEFmaHhiUSIsInR5cGUiOiJwYXktaW4ifQ==",
  reference: "foo",
  type: "pay-in",
  provider: "stripe",
  status: "succeeded",
  initialAmount: 12900,
  scheme: "mastercard",
  asset: "EUR/2",
  createdAt: "2022-08-09T15:41:24Z",
  raw: {
    amount: 12900,
    apiresource: {
      lastresponse: null,
    },
    availableon: 1660262400,
    created: 1660059684,
    currency: "eur",
    description: "",
    exchangerate: 0,
    fee: 0,
    feedetails: [],
    id: "txn_foo",
    net: 12900,
    object: "balance_transaction",
    reportingcategory: "charge",
    source: {
      applicationfee: null,
      charge: {
        amount: 12900,
        amountcaptured: 12900,
        amountrefunded: 0,
        apiresource: {
          lastresponse: null,
        },
        application: null,
        applicationfee: null,
        applicationfeeamount: 0,
        authorizationcode: "",
        balancetransaction: {
          amount: 0,
          apiresource: {
            lastresponse: null,
          },
          availableon: 0,
          created: 0,
          currency: "",
          description: "",
          exchangerate: 0,
          fee: 0,
          feedetails: null,
          id: "txn_foo",
          net: 0,
          object: "",
          reportingcategory: "",
          source: null,
          status: "",
          type: "",
        },
        billingdetails: {
          address: {
            city: "",
            country: "",
            line1: "",
            line2: "",
            postalcode: "",
            state: "",
          },
          email: "foo@formance.com",
          name: "",
          phone: "",
        },
        calculatedstatementdescriptor: "FOO.COM",
        captured: true,
        created: 1660059340,
        currency: "eur",
        customer: null,
        description: "",
        destination: null,
        dispute: null,
        disputed: false,
        failurebalancetransaction: null,
        failurecode: "",
        failuremessage: "",
        frauddetails: {
          stripereport: "",
          userreport: "",
        },
        id: "ch_foo",
        invoice: null,
        level3: {
          customerreference: "",
          lineitems: null,
          merchantreference: "",
          shippingaddresszip: "",
          shippingamount: 0,
          shippingfromzip: "",
        },
        livemode: true,
        metadata: {
          bo_link: "http://localhost",
          internal_fraud_scoring: "fraud_action_require_auth",
          order_id: "Vfoo",
          user_id: "33foo",
        },
        object: "charge",
        onbehalfof: null,
        order: null,
        outcome: {
          networkstatus: "approved_by_network",
          reason: "",
          risklevel: "normal",
          riskscore: 0,
          rule: null,
          sellermessage: "Payment complete.",
          type: "authorized",
        },
        paid: true,
        paymentintent: {
          amount: 0,
          amountcapturable: 0,
          amountdetails: null,
          amountreceived: 0,
          apiresource: {
            lastresponse: null,
          },
          application: null,
          applicationfeeamount: 0,
          automaticpaymentmethods: null,
          canceledat: 0,
          cancellationreason: "",
          capturemethod: "",
          charges: null,
          clientsecret: "",
          confirmationmethod: "",
          created: 0,
          currency: "",
          customer: null,
          description: "",
          id: "pi_foo",
          invoice: null,
          lastpaymenterror: null,
          livemode: false,
          metadata: null,
          nextaction: null,
          object: "",
          onbehalfof: null,
          paymentmethod: null,
          paymentmethodoptions: null,
          paymentmethodtypes: null,
          processing: null,
          receiptemail: "",
          review: null,
          setupfutureusage: "",
          shipping: {
            address: null,
            carrier: "",
            name: "",
            phone: "",
            trackingnumber: "",
          },
          source: null,
          statementdescriptor: "",
          statementdescriptorsuffix: "",
          status: "",
          transferdata: null,
          transfergroup: "",
        },
        paymentmethod: "src_foo",
        paymentmethoddetails: {
          achcredittransfer: null,
          achdebit: null,
          acssdebit: null,
          afterpayclearpay: null,
          alipay: null,
          aubecsdebit: null,
          bacsdebit: null,
          bancontact: null,
          boleto: null,
          card: {
            brand: "mastercard",
            checks: {
              addressline1check: "",
              addresspostalcodecheck: "",
              cvccheck: "pass",
            },
            country: "FR",
            description: "",
            expmonth: 12,
            expyear: 2023,
            fingerprint: "Cfoo",
            funding: "debit",
            iin: "",
            installments: null,
            issuer: "",
            last4: "3foo",
            mandate: "",
            moto: false,
            network: "cartes_bancaires",
            threedsecure: {
              authenticationflow: "challenge",
              result: "authenticated",
              resultreason: "",
              version: "2.1.0",
            },
            wallet: null,
          },
          cardpresent: null,
          customerbalance: null,
          eps: null,
          fpx: null,
          giropay: null,
          grabpay: null,
          ideal: null,
          interacpresent: null,
          klarna: null,
          konbini: null,
          multibanco: null,
          oxxo: null,
          p24: null,
          paynow: null,
          sepacredittransfer: null,
          sepadebit: null,
          sofort: null,
          stripeaccount: null,
          type: "card",
          usbankaccount: null,
          wechat: null,
          wechatpay: null,
        },
        receiptemail: "",
        receiptnumber: "",
        receipturl: "http//localhost",
        refunded: false,
        refunds: {
          apiresource: {
            lastresponse: null,
          },
          data: [],
          listmeta: {
            hasmore: false,
            totalcount: 0,
            url: "/bar/foo/ch_foo/refunds",
          },
        },
        review: null,
        shipping: null,
        source: {
          apiresource: {
            lastresponse: null,
          },
          bankaccount: null,
          card: null,
          deleted: false,
          id: "src_foo",
          sourceobject: {
            amount: 12900,
            apiresource: {
              lastresponse: null,
            },
            clientsecret: "src_client_secret_foo",
            codeverification: null,
            created: 1660059341,
            currency: "eur",
            customer: "",
            flow: "redirect",
            id: "src_foo",
            livemode: true,
            mandate: null,
            metadata: {},
            object: "source",
            owner: {
              address: {
                city: "",
                country: "",
                line1: "",
                line2: "",
                postalcode: "",
                state: "",
              },
              email: "foo@formance.com",
              name: "",
              phone: "",
              verifiedaddress: null,
              verifiedemail: "",
              verifiedname: "",
              verifiedphone: "",
            },
            receiver: null,
            redirect: {
              failurereason: "",
              returnurl: "stripejs://use_stripe_sdk/return_url",
              status: "not_required",
              url: "stripejs://use_stripe_sdk",
            },
            sourceorder: null,
            statementdescriptor: "",
            status: "consumed",
            type: "three_d_secure",
            typedata: {
              authenticated: true,
              brand: "MasterCard",
              card: "card_foo",
              card_automatically_updated: null,
              country: "FR",
              cvc_check: "pass",
              exp_month: 12,
              exp_year: 2023,
              fingerprint: "foo",
              funding: "debit",
              iin: null,
              last4: "3foo",
              three_d_secure: "optional",
            },
            usage: "single_use",
          },
          type: "source",
        },
        sourcetransfer: null,
        statementdescriptor: "",
        statementdescriptorsuffix: "",
        status: "succeeded",
        transfer: null,
        transferdata: null,
        transfergroup: "order_foo",
      },
      connectcollectiontransfer: null,
      dispute: null,
      feerefund: null,
      id: "ch_foo",
      issuingauthorization: null,
      issuingdispute: null,
      issuingtransaction: null,
      payout: null,
      refund: null,
      reversal: null,
      topup: null,
      transfer: null,
      type: "charge",
    },
    status: "pending",
    type: "charge",
  },
  adjustments: [
    {
      status: "succeeded",
      amount: 12900,
      date: "2022-08-09T15:41:24Z",
      raw: {
        amount: 12900,
        apiresource: {
          lastresponse: null,
        },
        availableon: 1660262400,
        created: 1660059684,
        currency: "eur",
        description: "",
        exchangerate: 0,
        fee: 0,
        feedetails: [],
        id: "txn_foo",
        net: 12900,
        object: "balance_transaction",
        reportingcategory: "charge",
        source: {
          applicationfee: null,
          charge: {
            amount: 12900,
            amountcaptured: 12900,
            amountrefunded: 0,
            apiresource: {
              lastresponse: null,
            },
            application: null,
            applicationfee: null,
            applicationfeeamount: 0,
            authorizationcode: "",
            balancetransaction: {
              amount: 0,
              apiresource: {
                lastresponse: null,
              },
              availableon: 0,
              created: 0,
              currency: "",
              description: "",
              exchangerate: 0,
              fee: 0,
              feedetails: null,
              id: "txn_foo",
              net: 0,
              object: "",
              reportingcategory: "",
              source: null,
              status: "",
              type: "",
            },
            billingdetails: {
              address: {
                city: "",
                country: "",
                line1: "",
                line2: "",
                postalcode: "",
                state: "",
              },
              email: "foo@formance.com",
              name: "",
              phone: "",
            },
            calculatedstatementdescriptor: "FOO.COM",
            captured: true,
            created: 1660059340,
            currency: "eur",
            customer: null,
            description: "",
            destination: null,
            dispute: null,
            disputed: false,
            failurebalancetransaction: null,
            failurecode: "",
            failuremessage: "",
            frauddetails: {
              stripereport: "",
              userreport: "",
            },
            id: "ch_foo",
            invoice: null,
            level3: {
              customerreference: "",
              lineitems: null,
              merchantreference: "",
              shippingaddresszip: "",
              shippingamount: 0,
              shippingfromzip: "",
            },
            livemode: true,
            metadata: {
              bo_link: "http://localhost",
              internal_fraud_scoring: "fraud_action_require_auth",
              order_id: "Vfoo",
              user_id: "3foo",
            },
            object: "charge",
            onbehalfof: null,
            order: null,
            outcome: {
              networkstatus: "approved_by_network",
              reason: "",
              risklevel: "normal",
              riskscore: 0,
              rule: null,
              sellermessage: "Payment complete.",
              type: "authorized",
            },
            paid: true,
            paymentintent: {
              amount: 0,
              amountcapturable: 0,
              amountdetails: null,
              amountreceived: 0,
              apiresource: {
                lastresponse: null,
              },
              application: null,
              applicationfeeamount: 0,
              automaticpaymentmethods: null,
              canceledat: 0,
              cancellationreason: "",
              capturemethod: "",
              charges: null,
              clientsecret: "",
              confirmationmethod: "",
              created: 0,
              currency: "",
              customer: null,
              description: "",
              id: "pi_foo",
              invoice: null,
              lastpaymenterror: null,
              livemode: false,
              metadata: null,
              nextaction: null,
              object: "",
              onbehalfof: null,
              paymentmethod: null,
              paymentmethodoptions: null,
              paymentmethodtypes: null,
              processing: null,
              receiptemail: "",
              review: null,
              setupfutureusage: "",
              shipping: {
                address: null,
                carrier: "",
                name: "",
                phone: "",
                trackingnumber: "",
              },
              source: null,
              statementdescriptor: "",
              statementdescriptorsuffix: "",
              status: "",
              transferdata: null,
              transfergroup: "",
            },
            paymentmethod: "src_foo",
            paymentmethoddetails: {
              achcredittransfer: null,
              achdebit: null,
              acssdebit: null,
              afterpayclearpay: null,
              alipay: null,
              aubecsdebit: null,
              bacsdebit: null,
              bancontact: null,
              boleto: null,
              card: {
                brand: "mastercard",
                checks: {
                  addressline1check: "",
                  addresspostalcodecheck: "",
                  cvccheck: "pass",
                },
                country: "FR",
                description: "",
                expmonth: 12,
                expyear: 2023,
                fingerprint: "Cfoo",
                funding: "debit",
                iin: "",
                installments: null,
                issuer: "",
                last4: "3foo",
                mandate: "",
                moto: false,
                network: "cartes_bancaires",
                threedsecure: {
                  authenticationflow: "challenge",
                  result: "authenticated",
                  resultreason: "",
                  version: "2.1.0",
                },
                wallet: null,
              },
              cardpresent: null,
              customerbalance: null,
              eps: null,
              fpx: null,
              giropay: null,
              grabpay: null,
              ideal: null,
              interacpresent: null,
              klarna: null,
              konbini: null,
              multibanco: null,
              oxxo: null,
              p24: null,
              paynow: null,
              sepacredittransfer: null,
              sepadebit: null,
              sofort: null,
              stripeaccount: null,
              type: "card",
              usbankaccount: null,
              wechat: null,
              wechatpay: null,
            },
            receiptemail: "",
            receiptnumber: "",
            receipturl: "http://localhost",
            refunded: false,
            refunds: {
              apiresource: {
                lastresponse: null,
              },
              data: [],
              listmeta: {
                hasmore: false,
                totalcount: 0,
                url: "/foo/bar/ch_foo/refunds",
              },
            },
            review: null,
            shipping: null,
            source: {
              apiresource: {
                lastresponse: null,
              },
              bankaccount: null,
              card: null,
              deleted: false,
              id: "src_foo",
              sourceobject: {
                amount: 12900,
                apiresource: {
                  lastresponse: null,
                },
                clientsecret: "src_client_secret_foo",
                codeverification: null,
                created: 1660059341,
                currency: "eur",
                customer: "",
                flow: "redirect",
                id: "src_foo",
                livemode: true,
                mandate: null,
                metadata: {},
                object: "source",
                owner: {
                  address: {
                    city: "",
                    country: "",
                    line1: "",
                    line2: "",
                    postalcode: "",
                    state: "",
                  },
                  email: "foo@formance.com",
                  name: "",
                  phone: "",
                  verifiedaddress: null,
                  verifiedemail: "",
                  verifiedname: "",
                  verifiedphone: "",
                },
                receiver: null,
                redirect: {
                  failurereason: "",
                  returnurl: "stripejs://use_stripe_sdk/return_url",
                  status: "not_required",
                  url: "stripejs://use_stripe_sdk",
                },
                sourceorder: null,
                statementdescriptor: "",
                status: "consumed",
                type: "three_d_secure",
                typedata: {
                  authenticated: true,
                  brand: "MasterCard",
                  card: "card_foo",
                  card_automatically_updated: null,
                  country: "FR",
                  cvc_check: "pass",
                  exp_month: 12,
                  exp_year: 2023,
                  fingerprint: "Cfoo",
                  funding: "debit",
                  iin: null,
                  last4: "3",
                  three_d_secure: "optional",
                },
                usage: "single_use",
              },
              type: "source",
            },
            sourcetransfer: null,
            statementdescriptor: "",
            statementdescriptorsuffix: "",
            status: "succeeded",
            transfer: null,
            transferdata: null,
            transfergroup: "order_foo",
          },
          connectcollectiontransfer: null,
          dispute: null,
          feerefund: null,
          id: "ch_foo",
          issuingauthorization: null,
          issuingdispute: null,
          issuingtransaction: null,
          payout: null,
          refund: null,
          reversal: null,
          topup: null,
          transfer: null,
          type: "charge",
        },
        status: "pending",
        type: "charge",
      },
      absolute: false,
    },
  ],
};
export const ledgers = {
  server: "numary-ledger",
  version: "v1.6.1",
  config: {
    storage: {
      driver: "postgres",
      ledgers: [LEDGER_SLUG, "investing-app-demo-11"],
    },
  },
};

// Search
export const transactionList1 = {
  cursor: {
    pageSize: 15,
    hasMore: true,
    total: { value: 7000, relation: "eq" },
    next: "eyJ0YXJnZXQiOiJUUkFOU0FDVElPTiIsInNvcnQiOlt7ImtleSI6InR4aWQiLCJvcmRlciI6ImRlc2MifV0sInNlYXJjaEFmdGVyIjpbNjk4NV0sImxlZGdlcnMiOlsiZm9vLXgtMSJdLCJzaXplIjoxNSwidGVybVBvbGljeSI6IiIsInJldmVyc2UiOmZhbHNlLCJ0ZXJtcyI6bnVsbH0K",
    data: range(15).map((value) => ({
      ...transaction,
      txid: value,
    })),
    previous: "",
  },
};
export const accountList1 = {
  cursor: {
    pageSize: 15,
    hasMore: true,
    total: { value: 6003, relation: "eq" },
    data: range(15).map((value) => ({
      ...account,
      address: `world:${value}:${+new Date()}`,
    })),
    next: "eyJ0YXJnZXQiOiJBQ0NPVU5UIiwic29ydCI6W3sia2V5IjoiYWRkcmVzcyIsIm9yZGVyIjoiZGVzYyJ9XSwic2VhcmNoQWZ0ZXIiOlsidXNlcnM6OTk1OndhbGxldCJdLCJsZWRnZXJzIjpudWxsLCJzaXplIjoxNSwidGVybVBvbGljeSI6IiIsInJldmVyc2UiOmZhbHNlLCJ0ZXJtcyI6bnVsbH0K",
    previous: "",
  },
};
export const paymentList1 = {
  cursor: {
    pageSize: 15,
    hasMore: true,
    total: { value: 6003, relation: "eq" },
    next: "eyJ0YXJnZXQiOiJBQ0NPVU5UIiwic29ydCI6W3sia2V5IjoiYWRkcmVzcyIsIm9yZGVyIjoiZGVzYyJ9XSwic2VhcmNoQWZ0ZXIiOlsidXNlcnM6OTg4OndpdGhkcmF3YWxzOjRheHFwMHBqcGw2ejVsOWUwIl0sImxlZGdlcnMiOm51bGwsInNpemUiOjE1LCJ0ZXJtUG9saWN5IjoiIiwicmV2ZXJzZSI6ZmFsc2UsInRlcm1zIjpudWxsfQo=",
    data: range(15).map((value) => {
      let type = "pay-in";
      let provider = "stripe";
      let status = "succeeded";
      if (value % 2 == 0) {
        type = "payout";
        provider = "mangopay";
        status = "failed";
      }

      return {
        ...payment,
        provider,
        status,
        type,
        id: `${value}.${+new Date()}`,
      };
    }),
    previous: "",
  },
};
export const autocomplete = {
  ACCOUNT: [
    {
      address: "world",
      balances: {
        "EUR/2": -10000000,
        "RBLX/6": -350000000,
        "SNAP/6": -1840000000,
      },
      metadata: {},
      volumes: {
        "EUR/2": { output: 10000000, input: 0 },
        "RBLX/6": { output: 350000000, input: 0 },
        "SNAP/6": { output: 1840000000, input: 0 },
      },
    },
  ],
  ASSET: [
    { account: "world", input: 0, name: "SNAP/6", output: 1840000000 },
    { account: "world", input: 0, name: "RBLX/6", output: 350000000 },
    { account: "world", input: 0, name: "EUR/2", output: 10000000 },
  ],
  TRANSACTION: [
    {
      metadata: {},
      postings: [
        {
          amount: 10000,
          asset: "EUR/2",
          destination: "payments:adyen:4AXQP0PJPL6Z5L9L5",
          source: "world",
        },
      ],
      reference: "",
      timestamp: "2022-08-18T14:44:06Z",
      txid: 6993,
    },
    {
      metadata: {},
      postings: [
        {
          amount: 350000,
          asset: "RBLX/6",
          destination: "teller:otc:nyse",
          source: "world",
        },
        {
          amount: 1840000,
          asset: "SNAP/6",
          destination: "teller:otc:nyse",
          source: "world",
        },
      ],
      reference: "",
      timestamp: "2022-08-18T14:44:06Z",
      txid: 6995,
    },
    {
      metadata: {},
      postings: [
        {
          amount: 10000,
          asset: "EUR/2",
          destination: "payments:adyen:4AXQP0PJPL6Z5L9KK",
          source: "world",
        },
      ],
      reference: "",
      timestamp: "2022-08-18T14:44:06Z",
      txid: 6986,
    },
  ],
};
